//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int id_registro { get; set; }
        public string accion { get; set; }
        public string tabla_afectada { get; set; }
        public Nullable<int> id_registro_afectado { get; set; }
        public string valor_anterior { get; set; }
        public string valor_nuevo { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string direccion_ip { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
