//------------------------------------------------------------------------------
// <auto-generated>
//     Added manually to support contacto_cliente entity used by controllers.
// </auto-generated>

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Collections.Generic;

   public partial class contacto_cliente
    {
        public int id_contacto { get; set; }
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string puesto { get; set; }

       public virtual cliente cliente { get; set; }
    }
}
