//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using Microsoft.AspNet.SignalR;

    public partial class CRM_RSGEntities : DbContext
    {
        public CRM_RSGEntities()
            : base("name=CRM_RSGEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<bitacora> bitacoras { get; set; }
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<notificacione> notificaciones { get; set; }
        public virtual DbSet<oportunidade> oportunidades { get; set; }
        public virtual DbSet<reporte> reportes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<tarea> tareas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }

        // ====================================================================
        // INTERCEPCIÓN AUTOMÁTICA CENTRALIZADA (CORRECCIÓN TOTAL DE SINTAXIS)
        // ====================================================================
        public override int SaveChanges()
        {
            // Capturamos los registros antes de guardar para saber qué módulos se actualizaron
            var registrosNuevos = ChangeTracker.Entries()
                .Where(x => x.State == EntityState.Added)
                .ToList();

            // Guardamos los cambios principales (Citas, Clientes, Tareas)
            int resultadoOriginal = base.SaveChanges();

            if (registrosNuevos.Any())
            {
                using (var dbNoti = new CRM_RSGEntities())
                {
                    bool huboAlertas = false;

                    foreach (var entrada in registrosNuevos)
                    {
                        // 1. Módulo de Citas (Manrique)
                        if (entrada.Entity is cita c)
                        {
                            string descCita = $"Se te ha asignado una nueva cita: {c.descripcion ?? "Reunión de actividad comercial"} en '{c.lugar ?? "Oficina"}' fijada para el {c.fecha.ToString("dd/MM/yyyy")} a las {c.hora}.";

                            // .notificaciones es la propiedad del contexto; 'notificacione' es la clase de la entidad
                            dbNoti.notificaciones.Add(new notificacione
                            {
                                id_usuario = c.id_usuario,
                                mensaje = descCita,
                                fecha = DateTime.Now,
                                leida = false
                            });
                            huboAlertas = true;
                        }

                        // 2. Módulo de Gestión de Clientes (Sebas)
                        // Evaluamos con la clase real 'cliente' (en singular)
                        if (entrada.Entity is cliente cl)
                        {
                            int idAsignado = cl.id_usuario ?? 1;
                            string descCliente = $"Nuevo cliente asignado: Se te ha asignado el cliente {cl.nombre} de la empresa {cl.empresa ?? "Particular"}.";

                            dbNoti.notificaciones.Add(new notificacione
                            {
                                id_usuario = idAsignado,
                                mensaje = descCliente,
                                fecha = DateTime.Now,
                                leida = false
                            });
                            huboAlertas = true;
                        }

                        // 3. Módulo de Tareas (Jair)
                        if (entrada.Entity is tarea t)
                        {
                            int idAsignadoTarea = t.id_usuario ?? 1;
                            string descTarea = $"Nueva tarea asignada: Tienes una actividad pendiente registrada bajo la categoría comercial.";

                            dbNoti.notificaciones.Add(new notificacione
                            {
                                id_usuario = idAsignadoTarea,
                                mensaje = descTarea,
                                fecha = DateTime.Now,
                                leida = false
                            });
                            huboAlertas = true;
                        }
                    }

                    if (huboAlertas)
                    {
                        dbNoti.SaveChanges();

                        // Disparador en tiempo real de SignalR
                        try
                        {
                            var hubContext = GlobalHost.ConnectionManager.GetHubContext("NotificationHub");
                            if (hubContext != null)
                            {
                                hubContext.Clients.All.notificarCambioSistema();
                            }
                        }
                        catch { }
                    }
                }
            }

            return resultadoOriginal;
        }
    }
}