//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRM_RSGEntities : DbContext
    {
        public CRM_RSGEntities()
            : base("name=CRM_RSGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora> bitacoras { get; set; }
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<notificacione> notificaciones { get; set; }
        public virtual DbSet<oportunidade> oportunidades { get; set; }
        public virtual DbSet<reporte> reportes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<tarea> tareas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
