//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_cliente
    {
        public int id_note { get; set; }
        public int id_cliente { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        public virtual cliente clientes { get; set; }
    }
}
