//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarea()
        {
            this.tarea_cliente = new HashSet<tarea_cliente>();
        }
    
        public int id_tarea { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string prioridad { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_limite { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<bool> alerta_disparada { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarea_cliente> tarea_cliente { get; set; }
    }
}
