//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRSG.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tareas
    {
        public int id_tarea { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string prioridad { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_limite { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
